update workflows

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -2,10 +2,10 @@ name: Deploy Resume to S3
 
 on:
   push:
-    branches: 
-    - 'main'
+    branches: ["main"]
+    #- 'main'
 env:
-  AWS_BUCKET_NAME: ""
+  AWS_BUCKET_NAME: "resume.iamnecs.com"
   AWS_REGION: "us-east-1"
   
 
@@ -23,6 +23,17 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
+      
+      - name: Deploy Code to S3
+        run: 
+          aws s3 sync /resume s3://${{ env.AWS_BUCKET_NAME }} \
+            --delete \
+            --acl public-read
+        
+      - name: Verify Deployment
+        run: |
+          aws s3 ls s3://${{ env.AWS_BUCKET_NAME }}/index.html || (echo "Error: index.html missing!" && exit 1)
+
 
 
  
